/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ['class'],
	content: [
		'./pages/**/*.{ts,tsx}',
		'./components/**/*.{ts,tsx}',
		'./app/**/*.{ts,tsx}',
		'./src/**/*.{ts,tsx}',
	],
	theme: {
		container: {
			center: true,
			padding: '2rem',
			screens: {
				'2xl': '1400px',
			},
		},
		extend: {
			fontFamily: {
				display: ['var(--font-satoshi)', 'system-ui', 'sans-serif'],
				default: ['var(--font-inter)', 'system-ui', 'sans-serif'],
			},
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary-500))',
					25: 'hsl(var(--primary-25))',
					50: 'hsl(var(--primary-50))',
					100: 'hsl(var(--primary-100))',
					200: 'hsl(var(--primary-200))',
					300: 'hsl(var(--primary-300))',
					400: 'hsl(var(--primary-400))',
					500: 'hsl(var(--primary-500))',
					600: 'hsl(var(--primary-600))',
					700: 'hsl(var(--primary-700))',
					800: 'hsl(var(--primary-800))',
					900: 'hsl(var(--primary-900))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				success: {
					DEFAULT: 'hsl(var(--success-500))',
					25: 'hsl(var(--success-25))',
					50: 'hsl(var(--success-50))',
					100: 'hsl(var(--success-100))',
					200: 'hsl(var(--success-200))',
					300: 'hsl(var(--success-300))',
					400: 'hsl(var(--success-400))',
					500: 'hsl(var(--success-500))',
					600: 'hsl(var(--success-600))',
					700: 'hsl(var(--success-700))',
					800: 'hsl(var(--success-800))',
					900: 'hsl(var(--success-900))',
					foreground: 'hsl(var(--success-foreground))',
				},
				info: {
					DEFAULT: 'hsl(var(--info-500))',
					25: 'hsl(var(--info-25))',
					50: 'hsl(var(--info-50))',
					100: 'hsl(var(--info-100))',
					200: 'hsl(var(--info-200))',
					300: 'hsl(var(--info-300))',
					400: 'hsl(var(--info-400))',
					500: 'hsl(var(--info-500))',
					600: 'hsl(var(--info-600))',
					700: 'hsl(var(--info-700))',
					800: 'hsl(var(--info-800))',
					900: 'hsl(var(--info-900))',
				},
				warning: {
					DEFAULT: 'hsl(var(--warning-500))',
					25: 'hsl(var(--warning-25))',
					50: 'hsl(var(--warning-50))',
					100: 'hsl(var(--warning-100))',
					200: 'hsl(var(--warning-200))',
					300: 'hsl(var(--warning-300))',
					400: 'hsl(var(--warning-400))',
					500: 'hsl(var(--warning-500))',
					600: 'hsl(var(--warning-600))',
					700: 'hsl(var(--warning-700))',
					800: 'hsl(var(--warning-800))',
					900: 'hsl(var(--warning-900))',
				},
				danger: {
					DEFAULT: 'hsl(var(--danger-500))',
					25: 'hsl(var(--danger-25))',
					50: 'hsl(var(--danger-50))',
					100: 'hsl(var(--danger-100))',
					200: 'hsl(var(--danger-200))',
					300: 'hsl(var(--danger-300))',
					400: 'hsl(var(--danger-400))',
					500: 'hsl(var(--danger-500))',
					600: 'hsl(var(--danger-600))',
					700: 'hsl(var(--danger-700))',
					800: 'hsl(var(--danger-800))',
					900: 'hsl(var(--danger-900))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--danger-500))',
					25: 'hsl(var(--danger-25))',
					50: 'hsl(var(--danger-50))',
					100: 'hsl(var(--danger-100))',
					200: 'hsl(var(--danger-200))',
					300: 'hsl(var(--danger-300))',
					400: 'hsl(var(--danger-400))',
					500: 'hsl(var(--danger-500))',
					600: 'hsl(var(--danger-600))',
					700: 'hsl(var(--danger-700))',
					800: 'hsl(var(--danger-800))',
					900: 'hsl(var(--danger-900))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			keyframes: {
				'accordion-down': {
					from: { height: 0 },
					to: { height: 'var(--radix-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--radix-accordion-content-height)' },
					to: { height: 0 },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
}
