import { inter, satoshi } from '@/styles/fonts'
import './globals.css'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils'
import Background from '@/components/home/background'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn(satoshi.variable, inter.variable)}>
				{children}
				<Background />
			</body>
		</html>
	)
}
